services:
  auth-db:
    image: mysql:8.0
    container_name: auth-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: xdhdt
    ports:
      - "3306:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p123456 --silent"]
      interval: 10s
      timeout: 5s
      retries: 6

  auth-backend:
    build:
      context: ./AuthService/backend
      dockerfile: Dockerfile.dev
    container_name: auth-backend
    restart: unless-stopped
    env_file:
      - AuthService/backend/.env.docker
    environment:
      CHOKIDAR_USEPOLLING: "1"
    ports:
      - "8000:8000"
    volumes:
      - ./AuthService/backend:/usr/src/app
      - auth-backend-node-modules:/usr/src/app/node_modules
    depends_on:
      auth-db:
        condition: service_healthy

volumes:
  auth-db-data:
  auth-backend-node-modules:
